name:                MLL
version:             0.1.0.0
github:              "BatiDyDx/MLL"
license:             BSD-3-Clause
author:              "Bautista Peirone"
maintainer:          "bautista.peirone@gmail.com"
copyright:           "2024 Bautista Peirone"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Domain Specific Language for Modal Logic Engineering
category:            DSL

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/MLL#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- array
# - pretty                              # HughesPJ
# - prettyprinter-compat-ansi-wl-pprint # ANSI.Leijen
- prettyprinter >= 1.7.1
- transformers
- mtl
- exceptions
- haskeline

default-extensions:
- PatternSynonyms

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  MLL-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MLL
    build-tools:
    - happy
